# Generated by Django 4.0 on 2022-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0002_destination_img_destination_name_destination_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
